### ISSUE TITLE
Does the OCR function work today? 

### ISSUE THREAD

**Issue by aakhter** [sawhney17/logseq-searchable#1]
I did the /perform action on the same block as the image, got a popup saying 'performing OCR'... then nothing. 

How would I know if it worked?

**Comment by sawhney17** [comment]
It should work. You should be getting a message saying results inserted. If you vote there file you should see an OCR block property be added

**Comment by krillin666** [comment]
I'm not able to use OCR also on my setup. The popup saying "performing OCR" appears but then also nothing.
In the dev console the related errors might be:
```
lsp://logseq.io/home/hidden/Documents/Logseq/PhD/assets/image_1650642506108_0.png:1 GET lsp://logseq.io/home/hidden/Documents/Logseq/PhD/assets/image_1650642506108_0.png net::ERR_FILE_NOT_FOUND
index.2df3e9e8.js:2 Uncaught TypeError: e.toBlob is not a function
    at HTMLImageElement.F.orientation (index.2df3e9e8.js:2)
    at Function.o.register.n.onerror (index.2df3e9e8.js:2)
    at HTMLImageElement.i.onerror (index.2df3e9e8.js:2)
```

**Comment by sawhney17** [comment]
Is this off-line? Looks to be an issue with the requisite language files have being able to download on your off-line computer. I'll see if I can package them manually

**Comment by aakhter** [comment]
> It should work. You should be getting a message saying results inserted. If you vote there file you should see an OCR block property be added

Unfortunately, all I see is the popup, no actual text gets inserted into the block. Is there a debug (not sure how) I can get for you?

**Comment by sawhney17** [comment]
Could you send a screenshot of the dev console?

Command option i on Mac and Ctrl shift I on windows.

**Comment by krillin666** [comment]
> Is this off-line? Looks to be an issue with the requisite language files have being able to download on your off-line computer. I'll see if I can package them manually
> […](#)
> On 22 Apr 2022, 7:53 PM +0400, krillin666 ***@***.***>, wrote: I'm not able to use OCR also on my setup. The popup saying "performing OCR" appears but then also nothing. In the dev console the related errors might be: lsp://logseq.io/home/hidden/Documents/Logseq/PhD/assets/image_1650642506108_0.png:1 GET lsp://logseq.io/home/hidden/Documents/Logseq/PhD/assets/image_1650642506108_0.png net::ERR_FILE_NOT_FOUND index.2df3e9e8.js:2 Uncaught TypeError: e.toBlob is not a function at HTMLImageElement.F.orientation (index.2df3e9e8.js:2) at Function.o.register.n.onerror (index.2df3e9e8.js:2) at HTMLImageElement.i.onerror (index.2df3e9e8.js:2) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I'm online !

**Comment by lpwxyz** [comment]
I'm getting the same error that @krillin666 mentioned , trying to use it online as well

**Comment by sawhney17** [comment]
Cool. I'll look into this today

**Comment by sawhney17** [comment]
The latest version should fix this issue

**Comment by lpwxyz** [comment]
it's working, thanks!
